### PR TITLE
Update targets to use new BSPs names

### PR DESCRIPTION
**Pull request by sjanc**

### CODE REVIEW

**Comment by sjanc** [comment]
@ccollins476ad   could you check newt_dump/ part of that PR?

**Comment by ccollins476ad** [comment]
I don't think the "dump" tests need to change.  The dump test contains its own stripped down copy of the core and nimble repos (it is just a test of the newt tool, so it should not break when other repos change).

**Comment by sjanc** [comment]
ah ok, now it makes sense,   I'll remove it :)

**Comment by ccollins476ad** [comment]
Remove what? :)  You didn't change the dump test in this PR, did you?

**Comment by sjanc** [comment]
I've removed changes to dump_test that reflected new bsp names :)

**Pull request merged**
